# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json
PackageIdentifier: Ludens.bkt2gh
PackageVersion: 0.1.1
MinimumOSVersion: 10.0.0.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: bkt2gh.exe
    PortableCommandAlias: bkt2gh
ArchiveBinariesDependOnPath: true
Commands:
  - bkt2gh
ReleaseDate: 2026-04-15
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/ludens/bkt-to-gh/releases/download/v0.1.1/bkt2gh_0.1.1_windows_amd64.zip
    InstallerSha256: C7C4AA7A9B4345F595533E5FC701C0B1D5542274AF7A28F5D3437BD89ABB3564
  - Architecture: arm64
    InstallerUrl: https://github.com/ludens/bkt-to-gh/releases/download/v0.1.1/bkt2gh_0.1.1_windows_arm64.zip
    InstallerSha256: F3F2CBEA3C1DD18DF43B418EAED791BC3ACE5609F8E5061EBE7281D619FAC7A9
ManifestType: installer
ManifestVersion: 1.10.0
